In [12]:
import tensorflow as tf
import numpy as np
print(tf.__version__)


1.4.0


In [ ]:
sess = tf.Session()

In [105]:
# 生产随机数做测试用
k = np.random.randint(100,size=(1,2,2,5))
print("-k array 1,2,2,5--")
print(k)

k = np.random.randint(100,size=(2,2,5))
print("-k array 2,2,5--")
print(k)

a = tf.convert_to_tensor(k)
print("-k to tensor a--")
print(a)
print(sess.run(a))

a=tf.expand_dims(a,0)
print("-tensor a expand-")
print(a)
print(sess.run(a))

image_permute = tf.transpose(a, perm=[0,3,1,2])
print(" a transpose [0,3,1,2]")
print(sess.run(image_permute))


-k array 1,2,2,5--
[[[[40 78 45 87 16]
   [28 45 67 66 78]]

  [[46  0 29 63 75]
   [35 53 93 33  2]]]]
-k array 2,2,5--
[[[84 83 48 54 32]
  [28 55 82 31 28]]

 [[94 74  8 99 32]
  [ 8 84 77 50 79]]]
-k to tensor a--
Tensor("Const_13:0", shape=(2, 2, 5), dtype=int32)
[[[84 83 48 54 32]
  [28 55 82 31 28]]

 [[94 74  8 99 32]
  [ 8 84 77 50 79]]]
-tensor a expand-
Tensor("ExpandDims_14:0", shape=(1, 2, 2, 5), dtype=int32)
[[[[84 83 48 54 32]
   [28 55 82 31 28]]

  [[94 74  8 99 32]
   [ 8 84 77 50 79]]]]
 a transpose [0,3,1,2]
[[[[84 28]
   [94  8]]

  [[83 55]
   [74 84]]

  [[48 82]
   [ 8 77]]

  [[54 31]
   [99 50]]

  [[32 28]
   [32 79]]]]


In [89]:
a = tf.random_normal(shape=[2,2,5],seed=1)
b = tf.expand_dims(a,0)
print(a)
print(sess.run(a))
print(b)
print(sess.run(b))

Tensor("random_normal_32:0", shape=(2, 2, 5), dtype=float32)
[[[-0.8113182   1.4845988   0.06532937 -2.4427042   0.0992484 ]
  [ 0.5912243   0.59282297 -2.1229296  -0.72289723 -0.05627038]]

 [[ 0.6435448  -0.26432407  1.8566332   0.5678417  -0.3828359 ]
  [-1.4853433   1.2617711  -0.02530608 -0.2646297   1.5328138 ]]]
Tensor("ExpandDims_12:0", shape=(1, 2, 2, 5), dtype=float32)
[[[[-0.7682365  -0.4501324   0.4401832  -0.24608992  0.0162221 ]
   [-0.79020566 -0.50659627 -0.14337528 -1.2017821  -0.09246821]]

  [[-1.3039256   1.047524    0.04390011 -0.44126952 -0.75028235]
   [ 0.37807205 -0.65357274  0.46196136  0.15013815  0.03461238]]]]


In [68]:
# 定义placeholder，做为tensorflow计算图的输入
num_frames = 5 
imageIn = tf.placeholder(shape=[None,2,2,num_frames], dtype=tf.float32)
print(sess.run(imageIn, feed_dict={imageIn:k}))

[[[[48. 15. 48.  1. 53.]
   [86. 48. 57. 84. 59.]]

  [[34. 52. 93. 75. 88.]
   [34. 17. 64. 71. 15.]]]]


In [70]:
# 使用transpose交换维度
image_permute = tf.transpose(imageIn, perm=[0,3,1,2])
print(sess.run(image_permute, feed_dict={imageIn:k}))

[[[[48. 86.]
   [34. 34.]]

  [[15. 48.]
   [52. 17.]]

  [[48. 57.]
   [93. 64.]]

  [[ 1. 84.]
   [75. 71.]]

  [[53. 59.]
   [88. 15.]]]]


In [72]:
image_reshape = tf.reshape(image_permute, [-1, 2, 2, 1])
print(image_reshape)
sess.run(image_reshape,feed_dict={imageIn:k})

Tensor("Reshape_4:0", shape=(?, 2, 2, 1), dtype=float32)


array([[[[48.],
         [86.]],

        [[34.],
         [34.]]],


       [[[15.],
         [48.]],

        [[52.],
         [17.]]],


       [[[48.],
         [57.]],

        [[93.],
         [64.]]],


       [[[ 1.],
         [84.]],

        [[75.],
         [71.]]],


       [[[53.],
         [59.]],

        [[88.],
         [15.]]]], dtype=float32)